### ISSUE TITLE
path in test

### ISSUE THREAD

**Issue by rohan099** [nobejs/discuss#3]
@rajeshn95 i added folder structure for relative path in stories like src\stories\tags\UserCanCreateTags\endpoint.spec.js and also added the path in endpoint.js but both my tests and endpoints  is giving this error 

![image](https://user-images.githubusercontent.com/73166799/147631709-f4e6b87b-2c2c-4821-8910-ece7ac4f0b22.png)

**Comment by rajeshn95** [comment]
@rohan099 what is your folder name? above you wrote `src\stories\tags\UserCanCreateTags\endpoint.spec.js` but while running command you are using `src\stories\Tags\UserCanCreateTags\endpoint.spec.js` this.

**Comment by rohan099** [comment]
> @rohan099 what is your folder name? above you wrote `src\stories\tags\UserCanCreateTags\endpoint.spec.js` but while running command you are using `src\stories\Tags\UserCanCreateTags\endpoint.spec.js` this.

that's a typo here but in folder i gave in caps @rajeshn95 

![image](https://user-images.githubusercontent.com/73166799/147633103-0a739f2b-7c58-4988-8571-c22c4356494d.png)

is there any other file where we need to add the folder name?
